shell = "zsh"

[plugins]

[plugins.zsh-syntax-highlighting]
github = "zsh-users/zsh-syntax-highlighting"

[plugins.zsh-autosuggestions]
github = "zsh-users/zsh-autosuggestions"

[plugins.powerlevel10k]
github = "romkatv/powerlevel10k"

[plugins.input]
github = "zimfw/input"

[plugins.completion]
github = "zimfw/completion"
