[tools]
kubecolor = "0.5.3"
"cargo:stu" = "latest"
slsa-verifier = "latest"
watchexec = "2.5.1"
terraform = "1.14.8"
"github:anomalyco/opencode" = "1.4.0"

[settings]
idiomatic_version_file_enable_tools = []
