[tools]
kubecolor = "0.8.0"
"cargo:stu" = "latest"
slsa-verifier = "latest"
watchexec = "2.7.4"
oh-my-posh = "31.4.1"
node = "26.8.1"
oh-my-pi = { version = "18.6.1", rename_exe = "omp" }

[settings]
idiomatic_version_file_enable_tools = []
lockfile = true
