#!/bin/sh

set -euf

draw() {
  chafa -f sixel -s "${width}x${height}" --animate off --polite on "$1"
  exit 1
}


hash() {
  if [ "$(uname)" = "Darwin" ]; then
    # macOS: use -f for format, different specifiers, and resolve symlinks manually
    resolved="$1"
    [ -L "$1" ] && resolved="$(cd "$(dirname "$1")" && pwd -P)/$(basename "$1")"
    cache="$HOME/.cache/lf/$(stat -f '%N%i%T%z%B%m' -- "$resolved" | shasum -a 256 | cut -d' ' -f1).jpg"
  else
    # Linux: use GNU stat
    cache="$HOME/.cache/lf/$(stat --printf '%n\0%i\0%F\0%s\0%W\0%Y' -- "$(readlink -f -- "$1")" | sha256sum | cut -d' ' -f1).jpg"
  fi
}

cache() {
  if ! [ -s "$cache" ]; then
    dir="$(dirname -- "$cache")"
    [ -d "$dir" ] || mkdir -p -- "$dir"
    "$@"
  fi
}

file="$1"
width="$2"
height="$3"
x="$4"
y="$5"


case "$(file -Lb --mime-type -- "$file")" in
  image/*)
    chafa -f sixel -s "${width}x${height}" --animate off --polite on "${file}"
    exit 0
    ;;
  video/*)
    hash "$file"
    cache ffmpegthumbnailer -i "${file}" -c jpg -s 0 -f -o "$cache"
    chafa -f sixel -s "${width}x${height}" --animate off --polite on "$cache"
    exit 1
    ;;
  text/*)
    bat --color always "$1"
    exit 1
    ;;
  application/pdf)
    hash "$file"
	  gs -o "$cache" -sDEVICE=pngalpha -dLastPage=1 "$file" >/dev/null
    chafa -f sixel -s "${width}x${height}" --animate off --polite on "$cache"
	  exit 1
	  ;;
esac
