#!/bin/sh

set -euf

file="$1"
width="$2"
height="$3"
x="$4"
y="$5"

draw() {
  kitten icat --silent --stdin no --transfer-mode file \
    --place "${width}x${height}@${x}x${y}" "$1" < /dev/null > /dev/tty
  exit 1
}

hash() {
  if [ "$(uname)" = "Darwin" ]; then
    resolved="$1"
    [ -L "$1" ] && resolved="$(cd "$(dirname "$1")" && pwd -P)/$(basename "$1")"
    cache="$HOME/.cache/lf/$(stat -f '%N%i%T%z%B%m' -- "$resolved" | shasum -a 256 | cut -d' ' -f1).jpg"
  else
    cache="$HOME/.cache/lf/$(stat --printf '%n\0%i\0%F\0%s\0%W\0%Y' -- "$(readlink -f -- "$1")" | sha256sum | cut -d' ' -f1).jpg"
  fi
}

cache() {
  if ! [ -s "$cache" ]; then
    dir="$(dirname -- "$cache")"
    [ -d "$dir" ] || mkdir -p -- "$dir"
    "$@"
  fi
}

case "$(file -Lb --mime-type -- "$file")" in
  image/*)
    draw "$file"
    ;;
  video/*)
    hash "$file"
    cache ffmpegthumbnailer -i "$file" -c jpg -s 0 -f -o "$cache"
    draw "$cache"
    ;;
  text/*)
    bat --color always "$file"
    exit 1
    ;;
  application/pdf)
    hash "$file"
    cache gs -o "$cache" -sDEVICE=pngalpha -dLastPage=1 "$file" >/dev/null
    draw "$cache"
    ;;
esac
